<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CountriesSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['code_2' => 'tr','name' => 'Türkiye'],
            ['code_2' => 'vi','name' => 'ABD Virgin Adaları'],
            ['code_2' => 'af','name' => 'Afganistan'],
            ['code_2' => 'ax','name' => 'Aland Adaları'],
            ['code_2' => 'de','name' => 'Almanya'],
            ['code_2' => 'us','name' => 'Amerika Birleşik Devletleri'],
            ['code_2' => 'um','name' => 'Amerika Birleşik Devletleri Küçük Dış Adaları'],
            ['code_2' => 'as','name' => 'Amerikan Samoası'],
            ['code_2' => 'ad','name' => 'Andora'],
            ['code_2' => 'ao','name' => 'Angola'],
            ['code_2' => 'ai','name' => 'Anguilla'],
            ['code_2' => 'aq','name' => 'Antarktika'],
            ['code_2' => 'ag','name' => 'Antigua ve Barbuda'],
            ['code_2' => 'ar','name' => 'Arjantin'],
            ['code_2' => 'al','name' => 'Arnavutluk'],
            ['code_2' => 'aw','name' => 'Aruba'],
            ['code_2' => 'qu','name' => 'Avrupa Birliği'],
            ['code_2' => 'au','name' => 'Avustralya'],
            ['code_2' => 'at','name' => 'Avusturya'],
            ['code_2' => 'az','name' => 'Azerbaycan'],
            ['code_2' => 'bs','name' => 'Bahamalar'],
            ['code_2' => 'bh','name' => 'Bahreyn'],
            ['code_2' => 'bd','name' => 'Bangladeş'],
            ['code_2' => 'bb','name' => 'Barbados'],
            ['code_2' => 'eh','name' => 'Batı Sahara'],
            ['code_2' => 'bz','name' => 'Belize'],
            ['code_2' => 'be','name' => 'Belçika'],
            ['code_2' => 'bj','name' => 'Benin'],
            ['code_2' => 'bm','name' => 'Bermuda'],
            ['code_2' => 'by','name' => 'Beyaz Rusya'],
            ['code_2' => 'bt','name' => 'Bhutan'],
            ['code_2' => 'zz','name' => 'Bilinmeyen veya Geçersiz Bölge'],
            ['code_2' => 'ae','name' => 'Birleşik Arap Emirlikleri'],
            ['code_2' => 'gb','name' => 'Birleşik Krallık'],
            ['code_2' => 'bo','name' => 'Bolivya'],
            ['code_2' => 'ba','name' => 'Bosna Hersek'],
            ['code_2' => 'bw','name' => 'Botsvana'],
            ['code_2' => 'bv','name' => 'Bouvet Adası'],
            ['code_2' => 'br','name' => 'Brezilya'],
            ['code_2' => 'bn','name' => 'Brunei'],
            ['code_2' => 'bg','name' => 'Bulgaristan'],
            ['code_2' => 'bf','name' => 'Burkina Faso'],
            ['code_2' => 'bi','name' => 'Burundi'],
            ['code_2' => 'cv','name' => 'Cape Verde'],
            ['code_2' => 'gi','name' => 'Cebelitarık'],
            ['code_2' => 'dz','name' => 'Cezayir'],
            ['code_2' => 'cx','name' => 'Christmas Adası'],
            ['code_2' => 'dj','name' => 'Cibuti'],
            ['code_2' => 'cc','name' => 'Cocos Adaları'],
            ['code_2' => 'ck','name' => 'Cook Adaları'],
            ['code_2' => 'td','name' => 'Çad'],
            ['code_2' => 'cz','name' => 'Çek Cumhuriyeti'],
            ['code_2' => 'cn','name' => 'Çin'],
            ['code_2' => 'dk','name' => 'Danimarka'],
            ['code_2' => 'dm','name' => 'Dominik'],
            ['code_2' => 'do','name' => 'Dominik Cumhuriyeti'],
            ['code_2' => 'tl','name' => 'Doğu Timor'],
            ['code_2' => 'ec','name' => 'Ekvator'],
            ['code_2' => 'gq','name' => 'Ekvator Ginesi'],
            ['code_2' => 'sv','name' => 'El Salvador'],
            ['code_2' => 'id','name' => 'Endonezya'],
            ['code_2' => 'er','name' => 'Eritre'],
            ['code_2' => 'am','name' => 'Ermenistan'],
            ['code_2' => 'ee','name' => 'Estonya'],
            ['code_2' => 'et','name' => 'Etiyopya'],
            ['code_2' => 'fk','name' => 'Falkland Adaları (Malvinalar]'],
            ['code_2' => 'fo','name' => 'Faroe Adaları'],
            ['code_2' => 'ma','name' => 'Fas'],
            ['code_2' => 'fj','name' => 'Fiji'],
            ['code_2' => 'ci','name' => 'Fildişi Sahilleri'],
            ['code_2' => 'ph','name' => 'Filipinler'],
            ['code_2' => 'ps','name' => 'Filistin Bölgesi'],
            ['code_2' => 'fi','name' => 'Finlandiya'],
            ['code_2' => 'fr','name' => 'Fransa'],
            ['code_2' => 'gf','name' => 'Fransız Guyanası'],
            ['code_2' => 'tf','name' => 'Fransız Güney Bölgeleri'],
            ['code_2' => 'pf','name' => 'Fransız Polinezyası'],
            ['code_2' => 'ga','name' => 'Gabon'],
            ['code_2' => 'gm','name' => 'Gambia'],
            ['code_2' => 'gh','name' => 'Gana'],
            ['code_2' => 'gn','name' => 'Gine'],
            ['code_2' => 'gw','name' => 'Gine-Bissau'],
            ['code_2' => 'gd','name' => 'Granada'],
            ['code_2' => 'gl','name' => 'Grönland'],
            ['code_2' => 'gp','name' => 'Guadeloupe'],
            ['code_2' => 'gu','name' => 'Guam'],
            ['code_2' => 'gt','name' => 'Guatemala'],
            ['code_2' => 'gg','name' => 'Guernsey'],
            ['code_2' => 'gy','name' => 'Guyana'],
            ['code_2' => 'za','name' => 'Güney Afrika'],
            ['code_2' => 'gs','name' => 'Güney Georgia ve Güney Sandwich Adaları'],
            ['code_2' => 'kr','name' => 'Güney Kore'],
            ['code_2' => 'cy','name' => 'Güney Kıbrıs Rum Kesimi'],
            ['code_2' => 'ge','name' => 'Gürcistan'],
            ['code_2' => 'ht','name' => 'Haiti'],
            ['code_2' => 'hm','name' => 'Heard Adası ve McDonald Adaları'],
            ['code_2' => 'in','name' => 'Hindistan'],
            ['code_2' => 'io','name' => 'Hint Okyanusu İngiliz Bölgesi'],
            ['code_2' => 'nl','name' => 'Hollanda'],
            ['code_2' => 'an','name' => 'Hollanda Antilleri'],
            ['code_2' => 'hn','name' => 'Honduras'],
            ['code_2' => 'hk','name' => 'Hong Kong SAR - Çin'],
            ['code_2' => 'hr','name' => 'Hırvatistan'],
            ['code_2' => 'iq','name' => 'Irak'],
            ['code_2' => 'vg','name' => 'İngiliz Virgin Adaları'],
            ['code_2' => 'ir','name' => 'İran'],
            ['code_2' => 'ie','name' => 'İrlanda'],
            ['code_2' => 'es','name' => 'İspanya'],
            ['code_2' => 'il','name' => 'İsrail'],
            ['code_2' => 'se','name' => 'İsveç'],
            ['code_2' => 'ch','name' => 'İsviçre'],
            ['code_2' => 'it','name' => 'İtalya'],
            ['code_2' => 'is','name' => 'İzlanda'],
            ['code_2' => 'jm','name' => 'Jamaika'],
            ['code_2' => 'jp','name' => 'Japonya'],
            ['code_2' => 'je','name' => 'Jersey'],
            ['code_2' => 'kh','name' => 'Kamboçya'],
            ['code_2' => 'cm','name' => 'Kamerun'],
            ['code_2' => 'ca','name' => 'Kanada'],
            ['code_2' => 'me','name' => 'Karadağ'],
            ['code_2' => 'qa','name' => 'Katar'],
            ['code_2' => 'ky','name' => 'Kayman Adaları'],
            ['code_2' => 'kz','name' => 'Kazakistan'],
            ['code_2' => 'ke','name' => 'Kenya'],
            ['code_2' => 'ki','name' => 'Kiribati'],
            ['code_2' => 'co','name' => 'Kolombiya'],
            ['code_2' => 'km','name' => 'Komorlar'],
            ['code_2' => 'cg','name' => 'Kongo'],
            ['code_2' => 'cd','name' => 'Kongo Demokratik Cumhuriyeti'],
            ['code_2' => 'cr','name' => 'Kosta Rika'],
            ['code_2' => 'kw','name' => 'Kuveyt'],
            ['code_2' => 'kp','name' => 'Kuzey Kore'],
            ['code_2' => 'mp','name' => 'Kuzey Mariana Adaları'],
            ['code_2' => 'cu','name' => 'Küba'],
            ['code_2' => 'kg','name' => 'Kırgızistan'],
            ['code_2' => 'la','name' => 'Laos'],
            ['code_2' => 'ls','name' => 'Lesotho'],
            ['code_2' => 'lv','name' => 'Letonya'],
            ['code_2' => 'lr','name' => 'Liberya'],
            ['code_2' => 'ly','name' => 'Libya'],
            ['code_2' => 'li','name' => 'Liechtenstein'],
            ['code_2' => 'lt','name' => 'Litvanya'],
            ['code_2' => 'lb','name' => 'Lübnan'],
            ['code_2' => 'lu','name' => 'Lüksemburg'],
            ['code_2' => 'hu','name' => 'Macaristan'],
            ['code_2' => 'mg','name' => 'Madagaskar'],
            ['code_2' => 'mo','name' => 'Makao S.A.R. Çin'],
            ['code_2' => 'mk','name' => 'Makedonya'],
            ['code_2' => 'mw','name' => 'Malavi'],
            ['code_2' => 'mv','name' => 'Maldivler'],
            ['code_2' => 'my','name' => 'Malezya'],
            ['code_2' => 'ml','name' => 'Mali'],
            ['code_2' => 'mt','name' => 'Malta'],
            ['code_2' => 'im','name' => 'Man Adası'],
            ['code_2' => 'mh','name' => 'Marshall Adaları'],
            ['code_2' => 'mq','name' => 'Martinik'],
            ['code_2' => 'mu','name' => 'Mauritius'],
            ['code_2' => 'yt','name' => 'Mayotte'],
            ['code_2' => 'mx','name' => 'Meksika'],
            ['code_2' => 'fm','name' => 'Mikronezya Federal Eyaletleri'],
            ['code_2' => 'md','name' => 'Moldovya Cumhuriyeti'],
            ['code_2' => 'mc','name' => 'Monako'],
            ['code_2' => 'ms','name' => 'Montserrat'],
            ['code_2' => 'mr','name' => 'Moritanya'],
            ['code_2' => 'mz','name' => 'Mozambik'],
            ['code_2' => 'mn','name' => 'Moğolistan'],
            ['code_2' => 'mm','name' => 'Myanmar'],
            ['code_2' => 'eg','name' => 'Mısır'],
            ['code_2' => 'na','name' => 'Namibya'],
            ['code_2' => 'nr','name' => 'Nauru'],
            ['code_2' => 'np','name' => 'Nepal'],
            ['code_2' => 'ne','name' => 'Nijer'],
            ['code_2' => 'ng','name' => 'Nijerya'],
            ['code_2' => 'ni','name' => 'Nikaragua'],
            ['code_2' => 'nu','name' => 'Niue'],
            ['code_2' => 'nf','name' => 'Norfolk Adası'],
            ['code_2' => 'no','name' => 'Norveç'],
            ['code_2' => 'cf','name' => 'Orta Afrika Cumhuriyeti'],
            ['code_2' => 'uz','name' => 'Özbekistan'],
            ['code_2' => 'pk','name' => 'Pakistan'],
            ['code_2' => 'pw','name' => 'Palau'],
            ['code_2' => 'pa','name' => 'Panama'],
            ['code_2' => 'pg','name' => 'Papua Yeni Gine'],
            ['code_2' => 'py','name' => 'Paraguay'],
            ['code_2' => 'pe','name' => 'Peru'],
            ['code_2' => 'pn','name' => 'Pitcairn'],
            ['code_2' => 'pl','name' => 'Polonya'],
            ['code_2' => 'pt','name' => 'Portekiz'],
            ['code_2' => 'pr','name' => 'Porto Riko'],
            ['code_2' => 're','name' => 'Reunion'],
            ['code_2' => 'ro','name' => 'Romanya'],
            ['code_2' => 'rw','name' => 'Ruanda'],
            ['code_2' => 'ru','name' => 'Rusya Federasyonu'],
            ['code_2' => 'sh','name' => 'Saint Helena'],
            ['code_2' => 'kn','name' => 'Saint Kitts ve Nevis'],
            ['code_2' => 'lc','name' => 'Saint Lucia'],
            ['code_2' => 'pm','name' => 'Saint Pierre ve Miquelon'],
            ['code_2' => 'vc','name' => 'Saint Vincent ve Grenadinler'],
            ['code_2' => 'ws','name' => 'Samoa'],
            ['code_2' => 'sm','name' => 'San Marino'],
            ['code_2' => 'st','name' => 'Sao Tome ve Principe'],
            ['code_2' => 'sn','name' => 'Senegal'],
            ['code_2' => 'sc','name' => 'Seyşeller'],
            ['code_2' => 'sl','name' => 'Sierra Leone'],
            ['code_2' => 'sg','name' => 'Singapur'],
            ['code_2' => 'sk','name' => 'Slovakya'],
            ['code_2' => 'si','name' => 'Slovenya'],
            ['code_2' => 'sb','name' => 'Solomon Adaları'],
            ['code_2' => 'so','name' => 'Somali'],
            ['code_2' => 'lk','name' => 'Sri Lanka'],
            ['code_2' => 'sd','name' => 'Sudan'],
            ['code_2' => 'sr','name' => 'Surinam'],
            ['code_2' => 'sy','name' => 'Suriye'],
            ['code_2' => 'sa','name' => 'Suudi Arabistan'],
            ['code_2' => 'sj','name' => 'Svalbard ve Jan Mayen'],
            ['code_2' => 'sz','name' => 'Svaziland'],
            ['code_2' => 'rs','name' => 'Sırbistan'],
            ['code_2' => 'cs','name' => 'Sırbistan-Karadağ'],
            ['code_2' => 'cl','name' => 'Şili'],
            ['code_2' => 'tj','name' => 'Tacikistan'],
            ['code_2' => 'tz','name' => 'Tanzanya'],
            ['code_2' => 'th','name' => 'Tayland'],
            ['code_2' => 'tw','name' => 'Tayvan'],
            ['code_2' => 'tg','name' => 'Togo'],
            ['code_2' => 'tk','name' => 'Tokelau'],
            ['code_2' => 'to','name' => 'Tonga'],
            ['code_2' => 'tt','name' => 'Trinidad ve Tobago'],
            ['code_2' => 'tn','name' => 'Tunus'],
            ['code_2' => 'tc','name' => 'Turks ve Caicos Adaları'],
            ['code_2' => 'tv','name' => 'Tuvalu'],
            ['code_2' => 'tm','name' => 'Türkmenistan'],
            ['code_2' => 'ug','name' => 'Uganda'],
            ['code_2' => 'ua','name' => 'Ukrayna'],
            ['code_2' => 'om','name' => 'Umman'],
            ['code_2' => 'uy','name' => 'Uruguay'],
            ['code_2' => 'qo','name' => 'Uzak Okyanusya'],
            ['code_2' => 'jo','name' => 'Ürdün'],
            ['code_2' => 'vu','name' => 'Vanuatu'],
            ['code_2' => 'va','name' => 'Vatikan'],
            ['code_2' => 've','name' => 'Venezuela'],
            ['code_2' => 'vn','name' => 'Vietnam'],
            ['code_2' => 'wf','name' => 'Wallis ve Futuna'],
            ['code_2' => 'ye','name' => 'Yemen'],
            ['code_2' => 'nc','name' => 'Yeni Kaledonya'],
            ['code_2' => 'nz','name' => 'Yeni Zelanda'],
            ['code_2' => 'gr','name' => 'Yunanistan'],
            ['code_2' => 'zm','name' => 'Zambiya'],
            ['code_2' => 'zw','name' => 'Zimbabve']
        ];

        foreach($data as $row){
            $this->db->table('countries')->insert($row);
        }
    }
}